INSERT INTO users (username, email, password, age_group, vaccination_status, positive_result_date, current_infected_flag, parosmia_flag, active_flag) VALUES('john_tanaka', 'j_tanaka@sample.com', '$2a$10$oDoJbs28OQ4Qyfkvge1Bv.NV4pr//W9tTiqpKJ4bI7Q3zW6ojPf.e', 3, 3, "2021-05-16", 0, 1, 1);
INSERT INTO users (username, email, password, age_group, vaccination_status, positive_result_date, current_infected_flag, parosmia_flag) VALUES('mickey_tannie', 'm_tannie@sample.com', '$2a$10$YSN2A4uNT/2U6F/ApeApMeGy0nGDozw9EdxGGXnBSh.wanUkhQ1J2', 5, 0, "2022-03-22", 1, 0);
INSERT INTO users (username, email, password, age_group) VALUES('robert', 'r_rockutena@sample.com', '$2a$10$Esabb8CrbXXtgbrzIixfeeCjIR/mWcx60d3RRyWeYUTmPGc9Aaqfi', 2);
INSERT INTO users (username, email, password, age_group, vaccination_status, positive_result_date, current_infected_flag, parosmia_flag) VALUES('pedro_rockstone', 'p_rockstone@sample.com', '$2a$10$IU0.INcIuVz20t6TusMokO/pGrlBglgg4KFNYuStIvrXqHngu4GU.', 3, 3, "2020-04-30", 0, 0);
INSERT INTO users (username, email, password, age_group) VALUES('dr_jun', 'd_jun@sample.com', '$2a$10$Hnzl3hle/u9dsiESao1bGO/uIEl./dTOyoW/hgjLRq8cmtNSzMru6', 2);
INSERT INTO users (username, email, password, age_group, admin_flag) VALUES ('ad_min', 'a_min@sample.com', '$2a$10$/dvGuix4w6j4pLe39p4umOHKOPzajJEg.J4rOBwWSSP3Fhw4K0QBu', 3, 1);

INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (1, 'I really hope to get back to my normal self soon', 'In November of 2020 I was contacted by track and trace and asked to self-isolate. The day later I began to experience symptoms. I was lethargic and my muscle ached. These symptoms were quickly followed by shortness of breath, then no taste and no smell. I also began to have headaches. I did contact my GP for advice but fortunately I didn’t need to go to hospital.', 10, '2021-01-01 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, created_at) VALUES (1, 'I dont remember a great deal', 'There is just my husband and myself at home now. I have hardly been out for a year only to the supermarket and to church and then I always wore a mask. One of our daughters has a young baby; so during the pandemic we have formed a support bubble so that I could help with child care.', '2021-01-02 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (1, 'My chest felt like an elephant was sitting it', 'I tested positive on the 18th of March, the symptoms started with extreme ear pain, I had never had any previous issues with my ears, and bouts of coughing that lasted all day. About a week before that I just felt off, like I was coming down with something.', 20, '2021-01-03 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at, active_flag) VALUES (1, 'I dont know how I caught COVID-19', 'On Tuesday 2nd June I began to feel nauseous and had loose bowels. I had recently started a new medication so put it down to side effects; I decided I would probably stop taking the medication if the side effects continued. The following Friday I began to feel like I had ice water running through my veins, no matter what I did I could not get warm. By the next morning I had a raging temperature and I was very weak, I could only get out of bed to crawl to the bathroom, I live alone in a small flat, so didn’t have far to move to get to the bathroom or the kitchen but could barely reach either, I would feel like I was going to faint.', 15, '2021-01-04 00:00:01.000000', 0);
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (1, 'I love burgers but they taste different now?', 'The title says it all. I lost my sense of taste and smell after getting covid. Now I have started to realize that my favourite burger is no longer delicious! What can I do? Will this go away?', 100, '2021-10-15 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (1, 'Best place to get burgers', 'I love burgers and now that I am out of quarantine, I wanted to ask for people’s recommendation on different burger restaurant.', 14, '2021-10-27 00:00:01.000000');

INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (1, 'Burger lover with Parosmia', 'Thanks everyone for their input. I found that for me, MorningStar veggie burger tasted the best. I wanted to post to let other burger lovers with Parosmia of this. ', 27, '2022-06-01 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'A Young Doctor is confused', 'At the Qattameya Primary Health Unit (PHU) in New Cairo, this young, energetic doctor roams the corridors of the unit to help those coming to receive the vaccine. She helps them to quickly finish their procedures, answers their questions and reassures them.', 10, '2021-01-01 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'A day at a Vaccine Center in New Cairo', 'By the end of November 2021, a total of 36.9 million vaccine doses have been administered in Egypt out of over 70 million doses of different types of vaccines delivered – most of which by UNICEF through the COVAX facility.', 20, '2021-01-02 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'Bathrooms Back to Service', 'Long hours of a night shift or waiting to get healthcare services at a Primary Healthcare Unit (PHU) with a broken bathroom that can hardly be used. This has been an unpleasant situation faced by many people at the PHU of Towwa village in Minya, Upper Egypt, which is the only place that provides free healthcare services to the people of the village.', 20, '2021-01-03 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at, active_flag) VALUES (2, 'Saving Water by Increasing Access', 'Orany is a father of 7 children in a small village in Minya. Like many of his neighbors he is working in the fields surrounding the village as a farmer, earning less than a couple of dollars per day. A very low and irregular income, on which all the family relies.', 15, '2021-01-04 00:00:01.000000', 0);
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'The last time we saw her it was just before Mothers Day at a family dinner', 'The family had all been together on the Saturday before Mothers Day, Anne-Marie had thought her 71 year old mother in-law, Sandra, had looked a little under the weather. Sandra was fit and active and there was no need for anyone to feel unduly concerned.', 30, '2021-01-05 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'I had the Big 3 Symptoms', 'I have worked in social care in Salford for more than 20 years, I am now in my 50’s To start with I worked for the council but now I work for a not for profit care organisation providing care and support for people living with Dementia as well as people with disabilities and older people.', 30, '2021-01-06 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'The tiredness is horrible', 'Before lockdown Vania was an active person who has always volunteered in her community and was and hopes to be again an active member of many groups and organisations working to make things better for people here in Salford.', 75, '2021-01-07 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'I had my sons and my own health to consider', 'I am a Nurse but I am due to take early retirement due to ill health. I have two sons aged 15 and 17. My husband died at home from lung cancer 2 months before I was diagnosed with breast cancer. I needed all my focus and strength to fight my cancer, I didn’t have time to grieve or process my husband’s death properly.', 10, '2021-01-08 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'No Energy 4 months on', 'I tested positive for COVID-19 in October 2020. I didn’t have the usual symptoms; I had a headache and back ache. I then slept and was bed ridden for 10 days.', 60, '2021-01-09 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'Our 9 year old Grandson tested positive', 'As I have a number of health problems, including asthma and my husband having prostate cancer for which he received intense radiotherapy and we are both being over 70, we have been extremely cautious in an attempt not to contract the virus.', 90, '2021-01-10 00:00:01.000000');

INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'How long should covid normally last?', 'About a month ago I got diagnosed with covid. My symptoms in the beginning included mild fever, coughing and body aches. Although the fever subsided, I still have the other symptoms even though it has been over a month. Has anyone else experienced something similar? ', 10, '2022-05-01 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'Still quarantined', 'Quarantine sucks, but I guess we are all going through the same thing… I recommend passing time by playing puzzle games, I ordered them online. ', 19, '2022-05-06 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'Are vaccines effective? ', 'I wanted to know if the vaccines for COVID-19 are effective at all. I have heard they are a scam and I don’t want to risk my health with unnecessary shots. ', 50, '2022-05-10 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (2, 'Long Covid', 'Just wanted to share my experience with long covid. After a month of symptoms (which included coughing and continuous body aches) I looked for answers here, to see if others had gone though the same. I learned that there is a thing called “long covid”, and got a lot of advice on how to pass the time until. This is also advice to other people who may be wondering why their symptoms last for so long.', 60, '2022-05-12 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (3, 'Mom with worries', 'I am posting to see if there are other mothers in this forum who’s children have covid. 2 days ago my kid was officially diagnosed with covid, and consequently has been pulled out from school until they get better. But I am afraid of the symptoms and side effects. Any recommendations?', 10, '2022-04-03 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (4, 'COVID-19 has hit this house', 'Around dinner time I’d realised I hadn’t eaten anything which for me isn’t normal so I made myself some cheese on toast ‘mmm’. About half an hour after eating that I started seeing stars and having hot flushes and I thought here we go I’m getting a migraine, bloody cheese & dairy always sets me off. So I take the rest of the day easy take my ‘migraleve’ tablets and go through the motions of a migraine for me which generally consists of me losing my 20/20 vision having big globs floating through my eyes, sore head and my body completely purging itself of my insides (got to say thankfully all bottom end this time ) normally I’m sick too but not today. I have a little sleep as a dark cold room normally helps me out too.', 1, '2021-01-01 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, created_at) VALUES (4, 'Being on the COVD-19 Coaster', 'I received a positive COVID test in October just after my 34th birthday. I decided to take the test after feeling very drained a few days before and having a very mild cough, this only lasted a day or two and so I felt bad for using a test as was adamant it would be returned negative.', '2021-01-02 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (4, 'The COVID-19 ward was a lonely and scary place', 'All through the pandemic, out of my family I was the one who has been paranoid about sticking to the rules. I wear a mask and wash my hands. I have been working from home and I try to go out a little as possible. Even when it was allowed to meet people in the garden, I didn’t. At Christmas when you could see people, I still said no.', 2, '2021-01-03 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (4, 'Quarantine sucks', 'This sucks, can’t do anything, can’t go anywhere.', 2, '2022-03-21 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (4, 'J&J vaccine didn’t work', 'I got covid even with the J&J vaccine. Don’t get that one, it’s a scam.', 2, '2022-03-26 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (4, 'Actually none of the vaccines work', 'You are all liars, none of the vaccines actually work.', 2, '2022-04-18 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (4, 'This has been such a horrible experience', 'Wanted to share about my experience with covid. It was rough! My whole body hurt, had fever, difficulty catching my breath and on top on that had to recover all by myself because of the quarantine. I couldn’t even have friends come and visit me. ', 2, '2022-04-19 00:00:01.000000');
INSERT INTO posts (create_user_id, title, content, like_count, created_at) VALUES (5, 'Looking for volunteers with Parosmia', 'I am a doctor from University of Taste in Tokyo, I am intrigued by the large amount of people who seem to experience changes in taste after having covid. I am looking for volunteers for an interview and a taste test. Please visit University of Taste website if you are interested. More information will be sent to participants.', 2, '2022-5-11 00:00:01.000000');

INSERT INTO post_ratings (post_id, user_id, rating) VALUES (5, 3, 1);
INSERT INTO post_ratings (post_id, user_id, rating) VALUES (30, 3, 1);
INSERT INTO post_ratings (post_id, user_id, rating) VALUES (27, 3, 1);
INSERT INTO post_ratings (post_id, user_id, rating) VALUES (5, 1, 1);

INSERT INTO post_reports (post_id, user_id, message, created_at) VALUES (9, 3, 'report message 1', '2022-01-01 00:00:01.000000');
INSERT INTO post_reports (post_id, user_id, message, created_at) VALUES (9, 1, 'report message 2', '2022-02-02 00:00:01.000000');
INSERT INTO post_reports (post_id, user_id, message, created_at) VALUES (17, 3, 'report message 3', '2022-03-01 00:00:01.000000');

INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (5, 3, 'I have the same thing happen to me. I have heard it could be this thing called Parosmia');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (5, 2, 'Not sure, when I got covid I lost my sense of smell, but regained it normally after a month or so. Maybe just wait?');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (18, 3, 'My symptoms only lasted one week');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (18, 1, 'I don’t know man, which vaccines have you had?');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (20, 1, 'I had Moderna. I think they are the best and widely available.');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (20, 4, 'I don’t think they are a scam, you can get them for free. I would recommend Moderna or Pfizer.');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (28, 3, 'Which vaccine did you get?');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (28, 1, 'Did you get the second dose / boosters? ');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (28, 2, 'You will get reported with that tone buddy.');
INSERT INTO post_comments (post_id, user_id, comment_content) VALUES (30, 1, 'I would be interested to join');

INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (21145,'Frito Lay Cracker Jack  Popcorn &amp; Peanuts, 1.25 oz', 'https://spoonacular.com/productImages/21145-90x90.jpeg', 2, 4, 2, 2);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (61911,'SNICKERS Singles Size Chocolate Candy Bars, 1.86 Oz', 'https://spoonacular.com/productImages/61911-312x231.jpg', 86, 43, 2, 33);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (580451,'Coke Classic 20 oz Soda Bottles (Pack of 10, Total of 200 FL OZ)', 'https://spoonacular.com/productImages/580451-312x231.jpeg', 10, 24, 44, 3);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (10184,'Mini Oreo', 'https://spoonacular.com/productImages/10184-312x231.jpeg', 20, 7, 7, 31);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (198653,'Sapporo Ichiban Miso Ramen Noodles, 3.5 oz, (Pack of, 24)', 'https://spoonacular.com/productImages/198653-312x231.jpeg', 10, 2, 1, 3);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (758829,'Tomatoes On The Vine, Per lb', 'https://spoonacular.com/productImages/758829-312x231.jpeg', 10, 2, 1, 3);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (759185,'Pineapple', 'https://spoonacular.com/productImages/759185-312x231.jpeg', 90, 33, 33, 4);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (720549,'Haribo, Sour Gold-bears', 'https://spoonacular.com/productImages/720549-312x231.jpeg', 1, 33, 44, 4);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (650911,'Japanese Kit Kat Strawberry Cheese Cake Flavor KitKat Chocolates', 'https://spoonacular.com/productImages/650911-312x231.jpeg', 1, 33, 44, 4);
INSERT INTO foods (id, name, photo_address, tastes_same_count, tastes_different_count, tastes_worse_count, no_tastes_count) VALUES (1900703,'Coke Zero Sugar 8 oz Glass Bottles - Pack of 6', 'https://spoonacular.com/productImages/1900703-312x231.jpeg', 11, 33, 24, 11);


INSERT INTO food_ratings (food_id, user_id, rating) VALUES (21145, 1, 0);
INSERT INTO food_ratings (food_id, user_id, rating) VALUES (580451, 1, 1);
INSERT INTO food_ratings (food_id, user_id, rating) VALUES (720549, 1, 2);
INSERT INTO food_ratings (food_id, user_id, rating) VALUES (61911, 1, 3);

INSERT INTO food_comments (food_id, user_id, comment_content, created_at) VALUES (21145, 1, 'John comment 1', '2022-01-10 00:00:01.000000');
INSERT INTO food_comments (food_id, user_id, comment_content) VALUES (580451, 1, 'John comment 2');
INSERT INTO food_comments (food_id, user_id, comment_content, created_at) VALUES (21145, 3, 'Roberta comment 1', '2022-01-25 00:00:01.000000');
INSERT INTO food_comments (food_id, user_id, comment_content) VALUES (720549, 1, 'John comment 3');
INSERT INTO food_comments (food_id, user_id, comment_content) VALUES (1900703, 1, 'John comment 4');

INSERT INTO food_requests (user_id, message, created_at) VALUES(1, 'message 1', '2022-01-10 00:00:01.000000');
INSERT INTO food_requests (user_id, message, created_at) VALUES(3, 'message 2', '2022-01-25 00:00:01.000000');
